WebShop/ViewModels/ConfirmOrderViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebShop.Models
{
    public class ConfirmOrderViewModel
    {
        public int TotalCost { get; set; }
    
        [Required(ErrorMessage = "Не указано имя покупателя")]
        [Display(Name = "ФИО получателя")]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Не указан почтовый индекс")]
        [Display(Name = "Почтовый индекс получателя")]
        public int PostIndex { get; set; }
    
        [Required(ErrorMessage = "Не указан адрес доставки")]
        [Display(Name = "Адрес доставки (город, улица, дом, квартира)")]
        public string Address { get; set; }
    
        [Required(ErrorMessage = "Не указан номер телефона")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Номер телефона получателя")]
        public string PhoneNumber { get; set; }
    
        public bool WasErrors { get; set; }
    }
}

WebShop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Contexts;
using WebShop.Data.Enums;
using WebShop.Data.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class CartController : Controller
    {
        private DataContext _context;
        private UserManager<User> _userManager;

        public CartController(DataContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> GetSocks()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return PartialView("Socks/SocksInCartsListPartial", new SocksListViewModel());
            
            var socks = FileDataProvider.Socks.ToList();
            var socksInCart = _context.SocksInCart
                .Where(x => x.CustomerId == user.Id);
            var viewModels = new List<SockViewModel>();
            foreach (var sockInCart in socksInCart)
            {
                var sock = socks.FirstOrDefault(x => x.Id == sockInCart.SockId);
                if (sock == null)
                    continue;

                var model = sock.ToViewModel(PageType.Cart);
                viewModels.Add(model);
            }

            int totalCost = viewModels.Sum(x => x.Price);
            return PartialView("Socks/SocksInCartsListPartial", new SocksListViewModel
            {
                Socks = viewModels,
                IsCart = true,
                TotalCost = totalCost
            });
        }

        [Authorize(Roles = "user")]
        [HttpGet]
        public async Task<IActionResult> GetCartInfoHome(int id, int? change)
        {
            return await CheckAndGetCartInfo(id, change, PageType.Home);
        }
        
        [Authorize(Roles = "user")]
        [HttpGet]
        public async Task<IActionResult> GetCartInfoCatalog(int id, int? change)
        {
            return await CheckAndGetCartInfo(id, change, PageType.Catalog);
        }
        
        [Authorize(Roles = "user")]
        [HttpGet]
        public async Task<IActionResult> GetCartInfoInCart(int id, int? change)
        {
            return await CheckAndGetCartInfo(id, change, PageType.Cart);
        }

        private async Task<IActionResult> CheckAndGetCartInfo(int id, int? change, PageType fromPage)
        {
            var model = new SockCartControlsModel
            {
                Id = id,
                FromPage = (int)fromPage
            };
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return PartialView("Socks/SockCartControlsPartial", model.WithCount(-1));
            
            string userId = user.Id;
            var sockInCart = _context.SocksInCart.FirstOrDefault(x => x.SockId == id && x.CustomerId == userId);
            
            if (sockInCart == null)
            {
                if (change == null || change.Value <= 0)
                    return PartialView("Socks/SockCartControlsPartial", model.WithCount(0));
                
                var sock = FileDataProvider.Socks.FirstOrDefault(x => x.Id == id);
                if (sock == null || sock.NotExists)
                    return PartialView("Socks/SockCartControlsPartial", model.WithCount(0));

                _context.SocksInCart.Add(new SockInCart
                {
                    SockId = id,
                    CustomerId = userId,
                    Count = change.Value
                });
                await _context.SaveChangesAsync();
                return PartialView("Socks/SockCartControlsPartial", model.WithCount(change.Value));
            }

            if (change == null)
                return PartialView("Socks/SockCartControlsPartial", model.WithCount(sockInCart.Count));

            sockInCart.Count += change.Value;
            await _context.SaveChangesAsync();
            
            if (sockInCart.Count > 0)
                return PartialView("Socks/SockCartControlsPartial", model.WithCount(sockInCart.Count));
            
            _context.SocksInCart.Remove(sockInCart);
            await _context.SaveChangesAsync();
            return PartialView("Socks/SockCartControlsPartial", model.WithCount(0));
        }

        [HttpGet]
        public async Task<IActionResult> GetTotalCartInfo()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return PartialView("CartInfoPartial", 0);

            var socksInCart = _context.SocksInCart
                .Where(x => x.CustomerId == user.Id);

            int totalCost = 0;
            foreach (var sockInCart in socksInCart)
            {
                var sock = FileDataProvider.Socks.FirstOrDefault(x => x.Id == sockInCart.SockId);
                if (sock == null)
                    continue;
                
                totalCost += sock.Price * sockInCart.Count;
            }
            
            return PartialView("CartInfoPartial", totalCost);
        }

        [Authorize(Roles = "user")]
        [HttpGet]
        public async Task<int> GetCartCount(int id)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return 0;
            
            string userId = user.Id;
            var sockInCart = _context.SocksInCart.FirstOrDefault(x => x.SockId == id && x.CustomerId == userId);

            if (sockInCart == null) return 0;
            return sockInCart.Count;
        }

        [Authorize(Roles = "user")]
        [HttpGet]
        public async Task<int> GetCartTotalCount()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return await Task.FromResult(0);
            
            string userId = user.Id;
            int count = 0;
            var socks = _context.SocksInCart.Where(x => x.CustomerId == userId);

            foreach (var sock in socks)
            {
                count += sock.Count;
            }
            
            return await Task.FromResult(count);
        }

        [Authorize(Roles = "user")]
        [HttpGet]
        public async Task<IActionResult> ClearCart()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return RedirectToAction("Index");

            var socksInCarts = _context.SocksInCart
                .Where(x => x.CustomerId == user.Id);
            
            foreach (var sockInCart in socksInCarts)
            {
                _context.SocksInCart.Remove(sockInCart);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "user")]
        [HttpGet]
        public async Task<IActionResult> ConfirmOrder()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return RedirectToAction("Index", "Home");
            
            var socksInCart = _context.SocksInCart
                .Where(x => x.CustomerId == user.Id);

            int totalCost = 0;
            foreach (var sockInCart in socksInCart)
            {
                var sock = FileDataProvider.Socks.FirstOrDefault(x => x.Id == sockInCart.SockId);
                if (sock == null)
                    continue;
                
                totalCost += sock.Price * sockInCart.Count;
            }

            var model = new ConfirmOrderViewModel
            {
                TotalCost = totalCost
            };
            return View(model);
        }

        [Authorize(Roles = "user")]
        [HttpPost]
        public async Task<IActionResult> ConfirmOrder(ConfirmOrderViewModel model)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return RedirectToAction("Index", "Home");

            if (!ModelState.IsValid)
            {
                model.WasErrors = true;
                return View(model);
            }

            var socksInCart = _context.SocksInCart
                .Where(x => x.CustomerId == user.Id);

            var order = new Order
            {
                Date = DateTime.Now.ToLongDateString(),
                Name = model.Name,
                Address = model.Address,
                PhoneNumber = model.PhoneNumber,
                PostIndex = model.PostIndex,
                TotalCost = model.TotalCost,
                Socks = socksInCart.Select(x => new SockInOrder
                {
                    SockId = x.SockId,
                    Count = x.Count
                }).ToList()
            };
            FileDataProvider.Orders.Add(order);
            FileDataProvider.Save();
            
            _context.SocksInCart.RemoveRange(socksInCart);
            await _context.SaveChangesAsync();

            return View("OrderConfirmed", model);
        }
    }
}

WebShop/Views/Cart/CartCountNavbarPartial.cshtml
@model int

@if (Model > 0)
{
    <span class="badge badge-pill bg-danger">@Model</span>
}

WebShop/Views/Cart/CartInfoPartial.cshtml
@model int

<br/>
@if (Model <= 0)
{
    <h4>Корзина пуста!</h4>
}
else
{
    <h5>Итого: @Model руб.</h5>
    <br/>
    <a asp-controller="Cart" asp-action="ConfirmOrder" class="btn btn-sm btn-outline-secondary">Подтвердить заказ</a>
    <a asp-controller="Cart" asp-action="ClearCart" class="btn btn-sm btn-outline-secondary">Очистить корзину</a>
}

WebShop/Views/Cart/ConfirmOrder.cshtml
@model ConfirmOrderViewModel

@{
    ViewBag.Title = "Подтверждение заказа";
    ViewBag.CurrentPage = "Cart";
    Layout = "_Layout";
}

@section Navigation
{
    @await Html.PartialAsync("NavigationPartial");
}

<div class="d-flex justify-content-center vertical-center">
    <div class="card w-100">
        <div class="card-header">
            <h1 class="h3 mb-3 fw-normal">Подтверждение заказа</h1>
        </div>
        <form method="post" asp-action="ConfirmOrder" asp-controller="Cart">
            <div class="card-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-floating">
                    <label asp-for="PostIndex"></label>
                    <input asp-for="PostIndex" type="text" class="form-control" placeholder="введите почтовый индекс..." value="@Model.Address"/>
                    <span asp-validation-for="PostIndex" class="text-danger"></span>
                </div>
                <hr/>
                <div class="form-floating">
                    <label asp-for="Address"></label>
                    <input asp-for="Address" type="text" class="form-control" placeholder="введите адрес доставки..." value="@Model.Address"/>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <hr/>
                <div class="form-floating">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" type="text" class="form-control" placeholder="введите ваше полное имя..." value="@Model.Name"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <hr/>
                <div class="form-floating">
                    <label asp-for="PhoneNumber"></label>
                    <input asp-for="PhoneNumber" type="number" class="form-control" placeholder="введите номер телефона..." value="@Model.PhoneNumber"/>
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <hr/>
                <div class="form-floating">
                    <label asp-for="TotalCost">Итоговая сумма заказа</label>
                    <input asp-for="TotalCost" type="hidden"/>
                    <p>@Model.TotalCost</p>
                </div>
            </div>
            <div class="card-footer">
                <button class="w-100 btn btn-lg btn-primary" type="submit">Подтвердить</button>
            </div>
        </form>
    </div>
</div>

WebShop/Views/Cart/Index.cshtml
@{
    ViewBag.Title = "Корзина";
    ViewBag.CurrentPage = "Cart";
    Layout = "_Layout";
}

@section Navigation
{
    @await Html.PartialAsync("NavigationPartial");
}

<div class="offset-top">
    <div id="grid"></div>
    <div id="cart-info" class="justify-content-center text-center"></div>
</div>

@section Scripts
{
    <script type="text/javascript" src="~/js/cart/cart.js?v=2"></script>
}

WebShop/Views/Cart/OrderConfirmed.cshtml
@model ConfirmOrderViewModel

@{
    ViewBag.Title = "Заказ оформлен!";
    ViewBag.CurrentPage = "Cart";
    Layout = "_Layout";
}

@section Navigation
{
    @await Html.PartialAsync("NavigationPartial");
}

<div class="d-flex justify-content-center vertical-center">
    <div class="card w-100">
        <div class="card-header">
            <h1 class="h3 mb-3 fw-normal">Заказ сформирован, спасибо за покупку! ! Возврат на главную страницу произойдёт через 5 секунд.</h1>
            <h4 class="mb-3 fw-normal">Информация о заказе:</h4>
        </div>
        <div class="card-body">
            <div class="form-floating">
                <label asp-for="Name">Полное имя покупателя:</label>
                <p>@Model.Name</p>
                <hr/>
                <br/>
            </div>
            <div class="form-floating">
                <label asp-for="Address">Адрес доставки</label>
                <p>@Model.Address</p>
                <hr/>
                <br/>
            </div>
            <div class="form-floating">
                <label asp-for="PhoneNumber">Номер телефона покупателя</label>
                <p>@Model.PhoneNumber</p>
                <hr/>
                <br/>
            </div>
            <div class="form-floating">
                <label asp-for="TotalCost">Итоговая сумма заказа</label>
                <p>@Model.TotalCost рублей</p>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/js/waitAndGoToIndex.js" asp-append-version="true"></script>
}