WebShop/ViewModels/HomeViewModel.cs
namespace WebShop.Models
{
    public class HomeViewModel
    {
        public string ImageLink;
        public string ImageCutLink;
    }
}

WebShop/Controllers/CatalogController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Contexts;
using WebShop.Data.Enums;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class CatalogController : Controller
    {
        private const int SocksOnIndexCount = 3;
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetSocks()
        {
            var socks = FileDataProvider.Socks
                .OrderBy(x => x.NotExists)
                .Select(x => x.ToViewModel(PageType.Catalog))
                .ToList();
            
            return PartialView("Socks/SocksListPartialNew", new SocksListViewModel
            {
                Socks = socks
            });
        }

        public async Task<IActionResult> GetSocksCart()
        {
            var socks = FileDataProvider.Socks
                .OrderBy(x => x.NotExists)
                .Select(x => x.ToViewModel(PageType.Catalog))
                .ToList();
            
            return await Task.FromResult(PartialView("Socks/SocksInCartsListPartial", new SocksListViewModel
            {
                Socks = socks
            }));
        }

        [HttpGet]
        public async Task<IActionResult> GetSocksIndex()
        {
            var random = new Random();
            var socks = FileDataProvider.Socks
                .OrderBy(x => x.NotExists)
                .ThenBy(x => random.Next(100))
                .Take(SocksOnIndexCount)
                .Select(x => x.ToViewModel(PageType.Home))
                .ToList();
            
            return await Task.FromResult(PartialView("Socks/SocksListPartialNew", new SocksListViewModel
            {
                Socks = socks
            }));
        }
    }
}

WebShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class HomeController : Controller
    {
        private HomeViewModel _model;

        public HomeController()
        {
            _model = new HomeViewModel
            {
                ImageLink = "../images/home.jpg",
                ImageCutLink = "../images/sockCut.jpg"
            };
        }

        public IActionResult Index()
        {
            return View(_model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebShop/Controllers/NewsController.cs
using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Contexts;
using WebShop.Data.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class NewsController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public NewsController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var models = FileDataProvider.News
                .Select(x => x.ToViewModel())
                .ToList();
            
            return View(models);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult AddOrEdit(int? id)
        {
            if (!id.HasValue)
                return View(new NewsViewModel { Id = -1 });
            
            var news = FileDataProvider.News.FirstOrDefault(x => x.Id == id);
            if (news == null)
                return RedirectToAction("Index");

            return View(news.ToViewModel());
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult AddOrEdit(NewsViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            
            var news = FileDataProvider.News.FirstOrDefault(x => x.Id == model.Id);
            if (news == null)
            {
                news = new News();
                news.Id = FileDataProvider.GetNewsId();
                FileDataProvider.News.Add(news);
            }
            
            SetDataForNews(news, model);
            FileDataProvider.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id)
        {
            var news = FileDataProvider.News.FirstOrDefault(x => x.Id == id);
            if (news == null)
                return RedirectToAction("Index");

            FileDataProvider.News.Remove(news);
            FileDataProvider.Save();
            return RedirectToAction("Index");
        }

        private void SetDataForNews(News news, NewsViewModel model)
        {
            news.Name = model.Name;
            news.Text = model.Text;
            
            if (model.File == null) return;
            
            string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images/news");
            string fileName = Guid.NewGuid() + "_" + model.File.FileName;
            string filePath = Path.Combine(uploadFolder, fileName);
            using var fileStream = new FileStream(filePath, FileMode.Create);
            model.File.CopyTo(fileStream);

            news.Picture = fileName;
        }
    }
}

WebShop/Controllers/ReviewsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Contexts;
using WebShop.Data.Enums;
using WebShop.Data.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class ReviewsController : Controller
    {
        private const int ReviewsOnIndexCount = 3;
        
        private DataContext _context;
        private UserManager<User> _userManager;

        public ReviewsController(DataContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            string userName = "";
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user != null)
                userName = user.UserName;
            
            var models = FileDataProvider.Reviews
                .Select(x => x.ToViewModel(_context, PageType.Reviews, userName))
                .ToList();
            
            return View(models);
        }

        [HttpGet]
        public async Task<IActionResult> GetReviewsIndex()
        {
            var random = new Random();
            var reviews = FileDataProvider.Reviews
                .OrderBy(x => random.Next(100))
                .Take(ReviewsOnIndexCount)
                .Select(x => x.ToViewModel(_context, PageType.Home))
                .ToList();

            return await Task.FromResult(PartialView("Reviews/ReviewsListPartial", reviews));
        }

        [HttpGet]
        public async Task<IActionResult> GetReviewModal(int id)
        {
            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == id);
            if (review == null)
                return await Task.FromResult(PartialView("Modals/ReviewModalPartial", null));
            
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = review.ToViewModel(_context, PageType.Reviews, user?.UserName);
            return await Task.FromResult(PartialView("Modals/ReviewModalPartial", model));
        }

        [HttpGet]
        [Authorize(Roles = "user")]
        public async Task<IActionResult> AddOrEdit(int id, int? fromPage)
        {
            var page = fromPage != null ? (PageType)fromPage.Value : PageType.Reviews;
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return RedirectToAction("Index");
            
            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == id);
            if (review == null)
                return View(new ReviewViewModel { Id = -1, FromPage = (int) PageType.Reviews });
            
            if (review.AuthorName != user.UserName)
                return RedirectToAction("Index");
            
            return View(review.ToViewModel(_context, page));
        }

        [HttpPost]
        [Authorize(Roles = "user")]
        public async Task<IActionResult> AddOrEdit(ReviewViewModel model)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return RedirectToAction("Index");
            
            if (!ModelState.IsValid)
                return View(model);

            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == model.Id);
            if (review == null)
            {
                review = new Review
                {
                    Id = FileDataProvider.GetReviewId(),
                    Date = DateTime.Now,
                    AuthorName = user.SiteName,
                    Image = string.IsNullOrWhiteSpace(user.Avatar) ? "human_default.jpg" : user.Avatar
                };
                SetDataForReview(model, review);
                FileDataProvider.Reviews.Add(review);
                FileDataProvider.Save();
            }
            else
            {
                if (user.Id != review.AuthorName)
                    return RedirectToAction("Index");
                
                SetDataForReview(model, review);
                FileDataProvider.Save();
            }

            return RedirectToAction("AddOrEdit", new { id = review.Id });
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id)
        {
            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == id);
            if (review != null)
            {
                FileDataProvider.Reviews.Remove(review);
                FileDataProvider.Save();
            }

            return RedirectToAction("Index");
        }

        private void SetDataForReview(ReviewViewModel model, Review review)
        {
            review.Rating = model.Rating;
            review.Text = model.Text;
        }
    }
}

WebShop/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewBag.Title = "Стельки на любой вкус и цвет";
    Layout = "_Layout";
}

@section Navigation
{
    <li class="nav-item">
        <a class="nav-link" href="#home">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#catalog">Каталог</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#instruction">Инструкция</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#reviews">Отзывы</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#contacts">Контакты</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="News" asp-action="Index">Новости</a>
    </li>
}

<!--- Start Home Section --->
<div id="home">
    @* Start Landing Page Section *@
    <div class="landing">
        <div class="home-wrap">
            <div class="home-inner" style="background-image: url(@Model.ImageLink)">
            </div>
        </div>
    </div>
    
    <div class="caption text-center text-white">
        <h1>Эксклюзивные стельки для Вашей обуви</h1>
        <h2>Кастомизируй свою обувь!</h2>
        @* <a class="btn btn-outline-light btn-secondary btn-lg" href="#catalog">Вот некоторые варианты</a> *@
    </div>
    @* End Landing Page Section *@
</div>
<!--- End Home Section --->

<div class="b-example-divider"></div>

<!--- Start Catalog Section --->
<div id="catalog" class="offset">
    @* Start Jumbotron *@
    <div class="jumbotron text-center">
        <div class="narrow">
            <div class="col-12">
                <h3 class="heading">Вот некоторые варианты</h3>
                <div class="heading-underline"></div>
            </div>
            
            <div id="socks-list"></div>
            
            <div class="heading-underline"></div>
            <div>
                <a class="btn btn-primary heading" asp-controller="Catalog" asp-action="Index">Открыть каталог</a>
            </div>
        </div>
    </div>
    @* End Jumbotron *@
</div>
<!--- End Catalog Section --->

<div class="b-example-divider"></div>

<!--- Start VideoCut Section --->
<div id="instruction" class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
            <h1 class="display-4 f2-bold lh-1 mb-3">Вы можете вырезать стельку по вашему размер ноги</h1>
            <p class="col-lg-12 fs-4">
                Если ваша старая стелька вытаскивается, то просто приложите её на новую и обрежьте по краю.
                Если нет, то замерьте длину стопы обуви рулеткой.
                На всех наших стельках есть вспомогательные линии, по которым, зная длину стопы, можно вырезать стельку.
            </p>
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
            <div class="p-4 p-md-5 border rounded-3 bg-light">
                <img src="@Model.ImageCutLink" class="img-thumbnail" alt="Вырезка стельки"/>
            </div>
        </div>
    </div>
</div>
<!--- End VideoCut Section --->

<div class="b-example-divider"></div>

<!--- Start Reviews Section --->
<div id="reviews" class="offset">
    @* Start Jumbotron *@
    <div class="jumbotron text-center">
        <div class="col-12">
            <h3 class="heading">Отзывы</h3>
            <div class="heading-underline"></div>
        </div>
        
        <div id="reviews-list"></div>
        
        <div class="heading-underline"></div>
        <div>
             @if (User.Identity != null && User.Identity.IsAuthenticated)
             {
                 <a class="btn btn-primary heading" asp-controller="Reviews" asp-action="AddOrEdit">Добавить отзыв</a>
                 <br/>
             }
            <a class="nav-link" asp-controller="Reviews" asp-action="Index">Просмотреть все отзывы</a>
        </div>
    </div>
    @* End Jumbotron *@
</div>
<!--- End Reviews Section --->

<div class="b-example-divider"></div>

<!--- Start Contacts Section --->
<div id="contacts" class="offset">
    <footer>
        <div class="jumbotron text-center">
            <div>
                <h3 class="heading">Контакты</h3>
                <div class="heading-underline"></div>
            </div>
            
            <div class="text-center">
                Телефон: +7(927)439-76-77
                <br/>
                Email: khasanovemil@yandex.ru
                <br/>
                WhatsApp:
                <img src="images/whatsAppLink.jpg" width="100" height="100"/>
                Telegram:
                <img src="images/TGLink.jpg" width="100" height="100"/>
            </div>
        </div>
    </footer>
</div>
<!--- End Contacts Section --->

<div class="modal fade" id="sockModal" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content" id="sockModalContent">
            
        </div>
    </div>
</div>

<div class="modal fade" id="reviewModal" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content" id="reviewModalContent">
            
        </div>
    </div>
</div>

@section Scripts
{
   <script src="~/js/home/socksIndex.js" asp-append-version="true"></script>
   <script src="~/js/home/reviewsIndex.js" asp-append-version="true"></script>
   <script src="~/js/home/main.js" asp-append-version="true"></script>
}