WebShop/Controllers/ReviewsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebShop.Data.Contexts;
using WebShop.Data.Enums;
using WebShop.Data.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class ReviewsController : Controller
    {
        private const int ReviewsOnIndexCount = 3;
        
        private DataContext _context;
        private UserManager<User> _userManager;

        public ReviewsController(DataContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            string userName = "";
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user != null)
                userName = user.UserName;
            
            var models = FileDataProvider.Reviews
                .Select(x => x.ToViewModel(_context, PageType.Reviews, userName))
                .ToList();
            
            return View(models);
        }

        [HttpGet]
        public async Task<IActionResult> GetReviewsIndex()
        {
            var random = new Random();
            var reviews = FileDataProvider.Reviews
                .OrderBy(x => random.Next(100))
                .Take(ReviewsOnIndexCount)
                .Select(x => x.ToViewModel(_context, PageType.Home))
                .ToList();

            return await Task.FromResult(PartialView("Reviews/ReviewsListPartial", reviews));
        }

        [HttpGet]
        public async Task<IActionResult> GetReviewModal(int id)
        {
            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == id);
            if (review == null)
                return await Task.FromResult(PartialView("Modals/ReviewModalPartial", null));
            
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = review.ToViewModel(_context, PageType.Reviews, user?.UserName);
            return await Task.FromResult(PartialView("Modals/ReviewModalPartial", model));
        }

        [HttpGet]
        [Authorize(Roles = "user")]
        public async Task<IActionResult> AddOrEdit(int id, int? fromPage)
        {
            var page = fromPage != null ? (PageType)fromPage.Value : PageType.Reviews;
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return RedirectToAction("Index");
            
            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == id);
            if (review == null)
                return View(new ReviewViewModel { Id = -1, FromPage = (int) PageType.Reviews });
            
            if (review.AuthorName != user.UserName)
                return RedirectToAction("Index");
            
            return View(review.ToViewModel(_context, page));
        }

        [HttpPost]
        [Authorize(Roles = "user")]
        public async Task<IActionResult> AddOrEdit(ReviewViewModel model)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
                return RedirectToAction("Index");
            
            if (!ModelState.IsValid)
                return View(model);

            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == model.Id);
            if (review == null)
            {
                review = new Review
                {
                    Id = FileDataProvider.GetReviewId(),
                    Date = DateTime.Now,
                    AuthorName = user.SiteName,
                    Image = string.IsNullOrWhiteSpace(user.Avatar) ? "human_default.jpg" : user.Avatar
                };
                SetDataForReview(model, review);
                FileDataProvider.Reviews.Add(review);
                FileDataProvider.Save();
            }
            else
            {
                if (user.Id != review.AuthorName)
                    return RedirectToAction("Index");
                
                SetDataForReview(model, review);
                FileDataProvider.Save();
            }

            return RedirectToAction("AddOrEdit", new { id = review.Id });
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id)
        {
            var review = FileDataProvider.Reviews.FirstOrDefault(x => x.Id == id);
            if (review != null)
            {
                FileDataProvider.Reviews.Remove(review);
                FileDataProvider.Save();
            }

            return RedirectToAction("Index");
        }

        private void SetDataForReview(ReviewViewModel model, Review review)
        {
            review.Rating = model.Rating;
            review.Text = model.Text;
        }
    }
}

WebShop/Controllers/SockController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebShop.Data.Contexts;
using WebShop.Data.Enums;
using WebShop.Data.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class SockController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SockController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index(int id, int fromPage)
        {
            var sock = FileDataProvider.Socks.FirstOrDefault(x => x.Id == id);
            if (sock == null)
                return RedirectToCatalog();

            var model = sock.ToViewModel((PageType) fromPage);
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetSockModal(int id)
        {
            var sock = FileDataProvider.Socks.FirstOrDefault(x => x.Id == id);
            if (sock == null)
                return await Task.FromResult(PartialView("Modals/SockModalPartial", null));
            
            var model = sock.ToViewModel(PageType.Home);
            return await Task.FromResult(PartialView("Modals/SockModalPartial", model));
        }

        [HttpGet]
        public IActionResult GoBack(int fromPage)
        {
            var page = (PageType)fromPage;
            return page switch
            {
                PageType.Cart => RedirectToCart(),
                PageType.Catalog => RedirectToCatalog(),
                PageType.Home => RedirectToMainIndex(),
                _ => throw new ArgumentOutOfRangeException(nameof(fromPage), fromPage, null)
            };
        }
        
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult AddOrEdit(int? id, int? fromPage)
        {
            var page = fromPage != null ? (PageType)fromPage.Value : PageType.Catalog;
            var sock = id != null ? FileDataProvider.Socks.FirstOrDefault(x => x.Id == id) : null;
            var model = sock != null ? sock.ToViewModel(page) : new SockViewModel { Id = -1, FromPage = 1 };

            if (sock != null)
            {
                string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images/socks");
                
                string filePath = Path.Combine(uploadFolder, sock.Image);
                using var fs = System.IO.File.OpenRead(filePath);
                
                var file = new FormFile(fs, 0, fs.Length, null, Path.GetFileName(fs.Name))
                {
                    Headers = new HeaderDictionary(),
                    ContentType = "application/pdf"
                };
                model.UploadedImage = file;
            }

            // model.AvailableBrands = GetAvailableBrands();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public IActionResult AddOrEdit(SockViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var sock = FileDataProvider.Socks.FirstOrDefault(x => x.Id == model.Id);
            if (sock == null)
            {
                if (model.UploadedImage == null)
                {
                    ModelState.AddModelError("UploadedImage", "Загрузите превью товара");
                    return View(model);
                }
                sock = new Sock
                {
                    Id = FileDataProvider.GetSockId()
                };
                if (!TrySetDataForSock(model, sock))
                    return View(model);
                
                FileDataProvider.Socks.Add(sock);
                FileDataProvider.Save();
            }
            else
            {
                if (!TrySetDataForSock(model, sock))
                    return View(model);

                FileDataProvider.Save();
            }

            return RedirectToIndex(model.Id);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id, int fromPage)
        {
            var sock = FileDataProvider.Socks.FirstOrDefault(x => x.Id == id);
            if (sock != null)
            {
                FileDataProvider.Socks.Remove(sock);
                FileDataProvider.Save();
            }

            return GoBack(fromPage);
        }

        private IActionResult RedirectToCatalog()
        {
            return RedirectToAction("Index", "Catalog");
        }
        
        private IActionResult RedirectToCart()
        {
            return RedirectToAction("Index", "Cart");
        }

        private IActionResult RedirectToIndex(int id)
        {
            return RedirectToAction("Index", new { id });
        }

        private IActionResult RedirectToMainIndex()
        {
            return RedirectToAction("Index", "Home");
        }

        private bool TrySetDataForSock(SockViewModel model, Sock sock)
        {
            if (model.UploadedImage != null)
            {
                if (!TryProcessUploadedImage(model.UploadedImage, out string fileName))
                    return false;
                
                sock.Image = fileName;
            }

            sock.Name = model.Name;
            sock.Description = model.Description;
            sock.Price = model.Price;
            sock.SockType = model.SockType;
            sock.NotExists = model.NotExists;

            return true;
        }
        
        private bool TryProcessUploadedImage(IFormFile file, out string fileName)
        {
            fileName = null;
            if (file == null)
                return false;

            string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images/socks");
            fileName = Guid.NewGuid() + "_" + file.FileName;
            string filePath = Path.Combine(uploadFolder, fileName);
            using var fileStream = new FileStream(filePath, FileMode.Create);
            file.CopyTo(fileStream);

            return true;
        }
    }
}

WebShop/Views/Shared/Modals/LoginModalPartial.cshtml
@model LoginViewModel

<div class="modal fade" id="loginModal" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="h3 mb-3 fw-normal">Введите логин и пароль</h1>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form method="post" asp-action="Login" asp-controller="Account" asp-route-returnUrl="@ViewBag.ReturnUrl">
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly"></div>
                    <input type="hidden" asp-for="ReturnUrl" value="@ViewBag.ReturnUrl"/>
                    <div class="form-floating">
                        <label asp-for="Email" for="floatingLogin">Логин</label>
                        <input asp-for="Email" name="login" class="form-control" id="floatingLogin" placeholder="введите ваш логин..."/>
                        <input type="checkbox" onclick="toggleFloatingPassword()" value="Show Password">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="form-floating">
                        <label asp-for="Password" for="floatingPassword">Пароль</label>
                        <input asp-for="Password" name="password" type="password" class="form-control" id="floatingPassword" placeholder="введите пароль..."/>
                        <input type="checkbox" onclick="toggleFloatingPasswordConfirm()" value="Show Password">
                        <span asp-validation-for="Password"></span>
                    </div>
                    <div class="checkbox mb-3">
                        <label asp-for="Remember">
                            <input asp-for="Remember" type="checkbox" value="remember"/>
                            Запомнить
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
                </div>
            </form>
        </div>
    </div>
</div>

WebShop/Views/Shared/Modals/RegisterModalPartial.cshtml
@model RegisterViewModel

<div class="modal fade" id="registerModal" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="h3 mb-3 fw-normal">Регистрация нового пользователя</h1>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form method="post" asp-action="Register" asp-controller="Account" asp-route-returnUrl="@ViewBag.ReturnUrl">
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly"></div>
                    <input type="hidden" asp-for="ReturnUrl" value="@ViewBag.ReturnUrl"/>
                    <div class="form-floating">
                        <label asp-for="Email" for="floatingLogin">Логин</label>
                        <input asp-for="Email" name="login" class="form-control" id="floatingLogin" placeholder="введите ваш логин..."/>
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="form-floating">
                        <label asp-for="Password" for="floatingPassword">Пароль</label>
                        <input asp-for="Password" name="password" type="password" class="form-control" id="floatingPassword" placeholder="введите пароль..."/>
                        <input type="checkbox" onclick="toggleFloatingPassword()" value="Show Password">
                        <span asp-validation-for="Password"></span>
                    </div>
                    <div class="form-floating">
                        <label asp-for="PasswordConfirm" for="floatingPasswordConfirm">Повторите пароль</label>
                        <input asp-for="PasswordConfirm" name="passwordConfirm" type="password" class="form-control" id="floatingPasswordConfirm" placeholder="повторите пароль..."/>
                        <input type="checkbox" onclick="toggleFloatingPasswordConfirm()" value="Show Password">
                        <span asp-validation-for="PasswordConfirm"></span>
                    </div>
                    <div class="checkbox mb-3">
                        <label asp-for="Remember">
                            <input asp-for="Remember" type="checkbox" value="remember"/>
                            Запомнить
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
                </div>
            </form>
        </div>
    </div>
</div>

WebShop/Views/Shared/Modals/ReviewModalPartial.cshtml
@model ReviewViewModel

@if (Model != null)
{
    <div class="modal-body">
        <div class="row">
            <div class="col-5">
                <img class="img-rounded" width="100%" src="@Model.ImageSrc" alt="Аватар пользователя"/>
            </div>
            <div class="col-7">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@Model.AuthorName</h4>
                <p>@Model.Text</p>
                <hr/>
                <h5>Дата @Model.Date</h5>
                <hr/>
                @if (Model.IsAuthor || User.Identity != null && User.IsInRole("admin"))
                {
                    <form asp-action="AddOrEdit" asp-controller="Reviews" method="get">
                        <input type="hidden" name="id" value="@Model.Id"/>
                        <input type="hidden" name="fromPage" value="@Model.FromPage"/>
                        <input type="submit" value="Редактировать"/>
                    </form>
                    <form asp-action="Delete" asp-controller="Reviews" method="post">
                        <input type="hidden" name="id" value="@Model.Id"/>
                        <input type="hidden" name="fromPage" value="@Model.FromPage"/>
                        <input type="submit" value="Удалить"/>
                    </form>
                }
            </div>
        </div>
    </div>
}

WebShop/Views/Shared/Modals/SockModalPartial.cshtml
@model SockViewModel

@if (Model != null)
{
    <div class="modal-body">
        <div class="row">
            <div class="col-5">
                <img class="img-rounded" width="100%" src="@Model.ImageSrc" alt="Изображение стельки"/>
            </div>
            <div class="col-7">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@Model.Name</h4>
                <p>@Model.Description</p>
                <hr/>
                <h5>Стоимость: @Model.Price руб.</h5>
                <hr/>
                @if (Model.NotExists)
                {
                    <h4 class="text-danger">Товара нет в наличии!</h4>
                }
                <form asp-action="Index" asp-controller="Sock" method="get">
                    <input type="hidden" name="id" value="@Model.Id"/>
                    <input type="hidden" name="fromPage" value="@Model.FromPage"/>
                    <input type="submit" value="Подробнее"/>
                </form>
                @if (User.Identity != null && User.Identity.IsAuthenticated && !Model.NotExists)
                {
                    <div class="btn-group">
                        <div class="cart-controls">
                            <input type="hidden" id="sockId" value="@Model.Id"/>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
}